### ISSUE TITLE
Missing required app icon 120 in Release mode when uploaded to App Store using Application Loader

### ISSUE THREAD

**Issue by whitewolf33** [Softeq/ImagePicker-xamarin-ios#18]
This issue is reproducible in iOS 11 only in the **Release** mode. Archiving the application and uploading it to App Store using Application Loader results in 

> "ERROR ITMS-90022: Missing required icon file. The bundle does not contain an app icon for iPhone / iPod Touch of exactly '120x120' pixels, in .png format for iOS versions >= 7.0.
> 
> Warning: Missing App Store Icon. iOS Apps must include a 1024x1024px App Store Icon in PNG format. Without providing the icon in the Asset Catalog or via iTunes Connect, apps cannot be submitted for App Review or Beta App Review"

If the reference to Softeq's ImagePicker library is removed, then there is no issues reported.

###Possible  Reason: 
In iOS 11, multiple app asset catalogs are merged into a single catalog and this causes the App Icons to be missed from the final solution. 

### Observations: 
This issue happens only in "Release" configuration and with any other configuration, this issue does not occur.

### Steps tried to overcome the issue:
Used Hosted VMs to build IPA using Azure DevOps but no luck
Used local machine to archive and upload but issue exists
Tried renaming the AppIcons folder in the end solution to something else but the issue prevails.
Verified info.plist has the CFBundleIcon information.
Opened the IPA to check if the icons are present 
### Consequences: 
The App cannot be released to App Store in Release Mode. 

### More information:
Xamarin Forms: 4.0.0.471375

Apple Developer Tools
Xcode 10.2.1 (14490.122)
Build 10E1001

Xamarin.iOS
Version: 12.8.0.2 (Visual Studio Community)
Hash: f2248ae6
Branch: d16-0
Build date: 2019-04-23 11:59:04-0400

[ImagePicker - 1.1.0](https://www.nuget.org/packages/ImagePicker/)

[SO](https://stackoverflow.com/questions/46690782/xamarin-ios-cannot-submit-to-itunes-missing-required-icon-file)

[Xamarin Forum](https://forums.xamarin.com/discussion/104004/missing-app-icon-after-updating-to-ios-11-sdk)

Source Control Info.plist section for App Icons
```
<key>CFBundleIcons</key>
	<dict>
		<key>CFBundlePrimaryIcon</key>
		<dict>
			<key>CFBundleIconName</key>
			<string>Icon</string>
			<key>CFBundleIconFiles</key>
			<array>
				<string>40.png</string>
				<string>58.png</string>
				<string>60.png</string>
				<string>80.png</string>
				<string>87.png</string>
				<string>120.png</string>
				<string>180.png</string>
				<string>1024.png</string>
			</array>
		</dict>
	</dict>
	<key>XSAppIconAssets</key>
<string>Assets.xcassets/MyIcon.appiconset</string>

```

Archived Package Content Info.plist section for App Icons
```
<key>CFBundleIcons</key>
	<dict>
		<key>CFBundlePrimaryIcon</key>
		<dict>
			<key>CFBundleIconFiles</key>
			<array>
				<string>MyIcon20x20</string>
				<string>MyIcon29x29</string>
				<string>MyIcon40x40</string>
				<string>MyIcon60x60</string>
			</array>
			<key>CFBundleIconName</key>
			<string>MyIcon</string>
		</dict>
	</dict>

```

**Comment by fryette** [comment]
Looks like this is Xamarin issue. But what we can to do it change pdf to @2x and @3x pngs.

**Comment by fryette** [comment]
@whitewolf33 Package was updated, please check it now.
https://www.nuget.org/packages/ImagePicker/1.1.1

Right now nuget will provide separate `ImagePicker.xcassets` with all files. 
Could you please check and confirm that everything is ok for now?

**Comment by whitewolf33** [comment]
Hi @fryette  - The issue does not exist with ImagePicker 1.1.2. Thank you for your prompt response. Amazing work and great contribution.
